-- 테이블
CREATE TABLE MEMBER(
    mno         NUMBER(6),
    memail      VARCHAR2(200) NOT NULL UNIQUE,
    mpasswd     VARCHAR2(200) NOT NULL,
    mname       VARCHAR2(30) NOT NULL,
    mgender     VARCHAR2(10) NOT NULL,
    mage        NUMBER(3) NOT NULL,
    maddr       VARCHAR2(1000) NOT NULL,
    mtel        VARCHAR2(15) NOT NULL,
    maccount    VARCHAR2(1000) NOT NULL,
    mauth       VARCHAR2(30) DEFAULT 'NORMAL',
    mstatus     VARCHAR2(200) DEFAULT 'ACTIVE',
    mdate       DATE DEFAULT SYSDATE,
    
    CONSTRAINT PK_MEMBER PRIMARY KEY(mno)
);

SELECT * FROM MEMBER WHERE MNAME = '테스트';

CREATE TABLE STORE(
    sno         NUMBER(6),
    sname       VARCHAR2(200) NOT NULL,
    sfiles      VARCHAR2(4000),
    scategory   VARCHAR2(100) NOT NULL,
    skeyword    VARCHAR2(200),
    scontent    VARCHAR2(4000) NOT NULL,
    saddr       VARCHAR2(1000) NOT NULL,
    ssido       VARCHAR2(100) NOT NULL,
    ssigungu    VARCHAR2(100) NOT NULL,
    slat        NUMBER(11,8) NOT NULL,
    slong       NUMBER(11,8) NOT NULL,
    stel        VARCHAR2(15),
    sinfo       VARCHAR2(4000),
    sparking    VARCHAR2(30) DEFAULT 'N',
    sstatus     VARCHAR2(30) DEFAULT 'OPEN',
    
    CONSTRAINT PK_STORE PRIMARY KEY(sno)
);

SELECT * FROM STORE ORDER BY SNO DESC;

SELECT * FROM MEMBER;

SELECT * FROM MENU ORDER BY MNNO DESC;

SELECT * FROM RATING;

SELECT * FROM ORDERS;

SELECT * FROM BOARD;

SELECT DISTINCT ssido 
FROM store 
WHERE ssido IS NOT NULL;

SELECT sno, sname, scategory, skeyword FROM store;

SELECT DISTINCT ssido, ssigungu
FROM store
WHERE ssido IS NOT NULL AND ssigungu IS NOT NULL
ORDER BY ssido, ssigungu;

CREATE TABLE MENU(
    mnno        NUMBER(6),
    mnname      VARCHAR2(100) NOT NULL,
    mnprice     NUMBER(7) NOT NULL,
    sno         NUMBER(6),
    
    CONSTRAINT PK_MENU PRIMARY KEY(mnno),
    CONSTRAINT FK_MENU_STORE 
     FOREIGN KEY(sno) REFERENCES STORE(sno) ON DELETE CASCADE
);

CREATE TABLE BOOKMARK(
    bmno        NUMBER(6),
    mno         NUMBER(6),
    sno         NUMBER(6),
    
    CONSTRAINT PK_BOOKMARK PRIMARY KEY(bmno),
    CONSTRAINT FK_BOOKMARK_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKMARK_STORE 
        FOREIGN KEY(sno) REFERENCES STORE(sno) ON DELETE CASCADE,
    CONSTRAINT UK_BOOKMARK
        UNIQUE(mno, sno)
);

CREATE TABLE PASS(
    pno         NUMBER(6),
    pimg        VARCHAR2(4000) NOT NULL,
    pname       VARCHAR2(100) NOT NULL,
    pprice      NUMBER(6) NOT NULL,
    pperiod     NUMBER(3),
    
    CONSTRAINT PK_PASS PRIMARY KEY(pno)
);

CREATE TABLE ORDERS(
    ono         VARCHAR2(50),
    oprice      NUMBER(7) NOT NULL,
    opayment    VARCHAR2(100) NOT NULL,
    odate       DATE DEFAULT SYSDATE,
    mno         NUMBER(6),
    
    CONSTRAINT PK_ORDERS PRIMARY KEY(ono),
    CONSTRAINT FK_ORDERS_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE
);

CREATE TABLE MEMBER_PASSES(
    mpno        NUMBER(6),
    mpstart     DATE DEFAULT SYSDATE,
    mpend       DATE NOT NULL,
    mpstatus    VARCHAR2(30) DEFAULT 'ACTIVE',
    mno         NUMBER(6),
    ono         VARCHAR2(50),
    pno         NUMBER(6),
    
    CONSTRAINT PK_MP PRIMARY KEY(mpno),
    CONSTRAINT FK_MP_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_MP_ORDERS 
        FOREIGN KEY(ono) REFERENCES ORDERS(ono) ON DELETE CASCADE,
    CONSTRAINT FK_MP_PASS 
        FOREIGN KEY(pno) REFERENCES PASS(pno) ON DELETE CASCADE
);

CREATE TABLE NOTICE(
    nno         NUMBER(6),
    ntitle      VARCHAR2(100) NOT NULL,
    ncontent    CLOB,
    nfiles      VARCHAR2(4000),
    ndate       DATE DEFAULT SYSDATE,
    nhit        NUMBER DEFAULT 0,
    mno         NUMBER(6),
    
    CONSTRAINT PK_NOTICE PRIMARY KEY(nno),
    CONSTRAINT FK_NOTICE_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE
);

CREATE TABLE BOARD(
    bno         NUMBER(6),
    btitle      VARCHAR2(100) NOT NULL,
    bcontent    CLOB,
    bcategory   VARCHAR2(20) NOT NULL,
    bdate       DATE DEFAULT SYSDATE,
    bhit        NUMBER DEFAULT 0,
    mno         NUMBER(6),
    
    CONSTRAINT PK_BOARD PRIMARY KEY(bno),
    CONSTRAINT FK_BOARD_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE
);

CREATE TABLE ANSWER(
    ano         NUMBER(6),
    acontent    CLOB NOT NULL,
    adate       DATE DEFAULT SYSDATE,
    mno         NUMBER(6),
    bno         NUMBER(6),
    
    CONSTRAINT PK_ANSWER PRIMARY KEY(ano),
    CONSTRAINT FK_ANSWER_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_ANSWER_BOARD 
        FOREIGN KEY(bno) REFERENCES BOARD(bno) ON DELETE CASCADE
);

CREATE TABLE RATING(
    rno         NUMBER(6),
    rtitle      VARCHAR2(100) NOT NULL,
    rcontent    CLOB,
    rrate       NUMBER(2,1) NOT NULL,
    rfeature    VARCHAR2(200),
    rdate       DATE DEFAULT SYSDATE,
    mno         NUMBER(6),
    sno         NUMBER(6),

    CONSTRAINT PK_RATING PRIMARY KEY(rno),
    CONSTRAINT FK_RATING_MEMBER
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_RATING_STORE
        FOREIGN KEY(sno) REFERENCES STORE(sno) ON DELETE CASCADE
);

-- 시퀀스
CREATE SEQUENCE MEMBER_SEQ
 START WITH 1
 INCREMENT BY 1;
 
CREATE SEQUENCE STORE_SEQ
 START WITH 10001
 INCREMENT BY 1;

CREATE SEQUENCE MENU_SEQ
 START WITH 20001
 INCREMENT BY 1;

CREATE SEQUENCE BOOKMARK_SEQ
 START WITH 80001
 INCREMENT BY 1;

CREATE SEQUENCE PASS_SEQ
 START WITH 30001
 INCREMENT BY 1;

CREATE SEQUENCE MP_SEQ
 START WITH 40001
 INCREMENT BY 1;
 
CREATE SEQUENCE NOTICE_SEQ
 START WITH 50001
 INCREMENT BY 1;

CREATE SEQUENCE BOARD_SEQ
 START WITH 60001
 INCREMENT BY 1;

CREATE SEQUENCE RATING_SEQ
 START WITH 70001
 INCREMENT BY 1;
 
CREATE SEQUENCE ANSWER_SEQ
 START WITH 80001
 INCREMENT BY 1;